package se.maokei.mserver.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.*;
import org.springframework.data.relational.core.mapping.Column;

import java.time.LocalDateTime;
import java.util.UUID;

@Getter
@Setter
public abstract class EntityMetadata  {
  @Schema(name = "id", description = "The generated ID when saved into the database")
  @Id
  private UUID id;

  @Schema(name = "createdAt", description = "Generated by database upon document creation")
  @CreatedDate
  @JsonFormat(pattern = "yyyy-mm-dd HH:mm:ss")
  @Column("created")
  private LocalDateTime created;

  @Schema(name = "updatedAt", description = "Generated by database upon document update")
  @LastModifiedDate
  @JsonFormat(pattern = "yyyy-mm-dd HH:mm:ss")
  private LocalDateTime updated;
}
