package se.maokei.mserver.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;

import java.time.LocalDateTime;

@Getter
@Setter
public abstract class EntityMetadata {
  private static final long serialVersionUID = 1L;
  @Schema(name = "id", description = "The generated ID when saved into the database")
  @Id
  private String id;
  @Schema(name = "createdAt", description = "Generated by database upon document creation")
  @CreatedDate
  @JsonFormat(pattern = "yyyy-mm-dd HH:mm:ss")
  private LocalDateTime createdAt;
  @Schema(name = "updatedAt", description = "Generated by database upon document update")
  @LastModifiedDate
  @JsonFormat(pattern = "yyyy-mm-dd HH:mm:ss")
  private LocalDateTime updatedAt;
}
