package se.maokei.mserver.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.*;
import org.springframework.data.relational.core.mapping.Column;

import java.time.LocalDateTime;

@Getter
@Setter
public abstract class EntityMetadata  {
  @Schema(name = "created", description = "Generated by database upon creation")
  @CreatedDate
  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
  @Column("created")
  private LocalDateTime created;

  @Schema(name = "updated", description = "Set by database upon update")
  @LastModifiedDate
  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
  @Column("updated")
  private LocalDateTime updated;

  public abstract void generateId();
}
