version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/mserver"
    schedule:
      interval: "weekly"
  - package-ecosystem:
    directory: "/mclient"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
