services:
  database:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mserver
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  adminer:
    image: 'adminer:latest'
    restart: always
    ports:
      - '8888:8080'
  #app:
  #  build: .
  #  ports:
  #    - "9000:8080"
  #  environment:
  #   SPRING_DATASOURCE_URL: jdbc:postgresql://db/tc
  #    SPRING_DATASOURCE_USERNAME: tc
  #    SPRING_DATASOURCE_PASSWORD: tc
  #  depends_on:
  #    - db
