FROM gradle:jdk21-alpine AS BUILD
WORKDIR /build
COPY .gradle/ .gradle
COPY build.gradle settings.gradle ./

COPY src ./src
RUN ls /tmp
RUN gradle build -x test

FROM eclipse-temurin:21-jre-alpine
EXPOSE 8080
WORKDIR /app

RUN ls /tmp
COPY --from=BUILD /tmp /tmp
COPY --from=build /build/build/libs/mserver-0.0.1-SNAPSHOT.jar /app/app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=docker", "-jar","/app.jar"]