version: "3.9"

services:
  app:
    build: .
    restart: always
    environment:
      #- SPRING_DATA_MONGODB_HOST=mongo_db
      #- SPRING_DATA_MONGODB_PORT=27017
      #- SPRING_DATA_MONGODB_DATABASE=testdb
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/testdb
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    restart: always
    networks:
      - my-network
    ports:
      - 27017:27017

networks:
  my-network:
    driver: bridge