version: "3.9"

services:
  app:
    depends_on:
      - mongo
    build: .
    ports:
      - 8080:8080
    #environment:
      #- SPRING_DATA_MONGO_HOST=mongo
      #- SPRING_DATA_MONGO_DATABASE=mserver
      #- SPRING_DATA_MONGO_PORT=27017
    networks:
      - our-net
  database:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mserver
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - our-net
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - our-net
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - our-net
networks:
  our-net: