version: "3.9"

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    restart: always
    networks:
      - my-network
    ports:
      - 27017:27017

networks:
  my-network:
    driver: bridge