#open-api
springdoc:
  api-docs:
    enabled: true
# swagger-ui custom path
# springdoc.swagger-ui.path=/swagger-ui.html
app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
    iteration: 33
    keylength: 256

spring:
  data:
    mongodb:
      auto-index-creation: true
  profiles:
    active: test
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mserver
      auto-index-creation: true
      authentication-database: admin
      username: root
      password: example
---
spring:
  config:
    activate:
      on-profile:
        - test
---