name: Backend-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: mserver
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
